name: entregas
description: "O Entregas é um sistema web e móvel de delivery, a fim de otimizar o fluxo de entrega de pedidos e simplificar o comércio digital de micro e pequenas empresas."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter
 
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  validatorless: ^1.2.3
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  get_it: ^7.7.0
  flutter_mobx: ^2.2.1+1
  flutter_getit: ^2.0.0
  mobx: ^2.3.3+2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Martel Sans
      fonts:
        - asset: assets/fonts/MartelSans-SemiBold.ttf
          weight: 600